/**
 * Babel config file.
 *
 * @since 1.0.0
 *
 * @note Babel doesn't know where this file lives.
 * If you ever need to call Babel directly be sure to tell it.
 * It's not an issue at this time because we don't call it directly.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * This file and the contents of it are updated automatically.
 * - Instead of editing this file, please review source repository {@see https://o5p.me/LevQOD}.
 */
/* eslint-env node */

module.exports = function ( api ) {
	api.cache( false );

	return {
		presets : [ '@babel/preset-env', '@babel/preset-react', '@linaria' ],
	};
};
