/**
 * Cssnano config file.
 *
 * @since 1.0.0
 *
 * @note Cssnano doesn't know where this file lives.
 * If you ever need to call cssnano directly be sure to tell it.
 * It's not an issue at this time because we don't call it directly.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * This file and the contents of it are updated automatically.
 * - Instead of editing this file, please review source repository {@see https://o5p.me/LevQOD}.
 */
/* eslint-env node */

module.exports = {
	preset : [
		'default',
		{
			discardComments : {
				removeAll : true,
			},
		},
	],
};
