/**
 * Tailwind CSS config file.
 *
 * @since 1.0.0
 *
 * @note Tailwind doesn't know where this file lives.
 * If you ever need to call tailwind directly be sure to tell it.
 * It's not an issue at this time because we don't call it directly.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * This file and the contents of it are updated automatically.
 *
 * - Instead of editing this file, please configure `../../../composer.json`. See instructions below.
 * - Instead of editing this file, please review source repository {@see https://o5p.me/LevQOD}.
 */
/* eslint-env node */

/* @formatter:ignore
-----------------------------------------------------------------------------------------------------------------------
Example `extra.clevercanyon.&.tailwind` in `../../../composer.json`:
-----------------------------------------------------------------------------------------------------------------------
"extra" : {
	"clevercanyon" : {
		"&" : {
			"tailwind" : {
				"theme" : {
					"fontFamily" : {
						"sans"  : [ "Georama", "sans-serif" ],
						"serif" : [ "Georgia", "serif" ]
					}
				}
			}
		}
	}
}
-----------------------------------------------------------------------------------------------------------------------
Example `index.scss` starter file contents:
-----------------------------------------------------------------------------------------------------------------------
@import 'https://fonts.googleapis.com/css2?family=Georama:ital,wght@0,100..900;1,100..900&display=swap';

@tailwind base;
@tailwind components;
@tailwind utilities;
------------------------------------------------------------------------------------------------- @formatter:/ignore */

const fs   = require( 'fs' );
const path = require( 'path' );
const mc   = require( '@clevercanyon/js-object-mc' );

module.exports = ( () => {
	const file = {
		'composer.json' : {},
		'package.json'  : {},
	};
	try { file[ 'composer.json' ] = require( '../../../composer.json' ); } catch ( e ) {}
	try { file[ 'package.json' ] = require( '../../../package.json' ); } catch ( e ) {}

	return mc.merge(
		{
			theme   : {
				fontFamily : {
					sans  : [ 'Georama', 'sans-serif' ],
					serif : [ 'Georgia', 'serif' ],
				},
			},
			content : fs.existsSync( '../../../trunk' )
				? [ '../../../trunk/src/{**/*,**/.*,.*,*}.{md,xml,htm,html,php,jsx,js,cjs,tsx,ts,cts}' ]
				: [ '../../../src/{**/*,**/.*,.*,*}.{md,xml,htm,html,php,jsx,js,cjs,tsx,ts,cts}' ],
		},
		file[ 'composer.json' ]?.extra?.clevercanyon?.[ '&' ]?.tailwind || {},
		file[ 'package.json' ]?.config?.clevercanyon?.[ '&' ]?.tailwind || {},
	);
} )();
