/**
 * Babel config file.
 *
 * @since 1.0.0
 *
 * @note Babel is aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * This file and the contents of it are updated automatically.
 * Instead of editing, please review source repository {@see https://o5p.me/LevQOD}.
 */
/* eslint-env node */

module.exports = function ( api ) {
	api.cache( false );

	return {
		presets : [ '@babel/preset-env', '@babel/preset-react', '@linaria' ],
	};
};
