#!/usr/bin/env bash
##
# Last generated : 02-17-2022
# Expires on     : 03-19-2023
#
# Do not run this again before carefully considering.
# The certificates generated by this script are likely already
# set as trusted by macOS for those working at Clever Canyon.
##
# ---------------------------------------------------------------------------------------------------------------------
# To generate new keys/certificates:
# ---------------------------------------------------------------------------------------------------------------------
# $ ./ssl-ri-cas.sh generate;
# ---------------------------------------------------------------------------------------------------------------------

# ---------------------------------------------------------------------------------------------------------------------
# Tell macOS to trust; i.e., add root & intermediate CAs to system keychain:
# ---------------------------------------------------------------------------------------------------------------------
# $ ./ssl-ri-cas.sh add-to-mac-keychain;
# ---------------------------------------------------------------------------------------------------------------------

if [[ "${1:-}" == 'generate' ]]; then
	# Prep config dir.

	rm -rf ./.ssl-openssl;
	mkdir -p ./.ssl-openssl/newcerts;
	touch ./.ssl-openssl/index.txt;

	# Maximum valid days.

	days=395; # {@see https://o5p.me/Fz1NWM}.

	# Self-signed root CA generator.

	openssl genrsa -out ./.ssl-r-ca-key.pem 4096;
	openssl genrsa -out ./.ssl-i-ca-key.pem 4096;

	# Root CA.

	openssl req -config ./.ssl-openssl.cnf -extensions v3_ca \
		-new \
		-x509 \
		-nodes \
		-sha512 \
		-days "${days}" \
		-key ./.ssl-r-ca-key.pem \
		-out ./.ssl-r-ca-crt.pem \
		-subj "/C=US/ST=GA/L=Johns Creek/O=Clever Canyon/OU=Engineering/CN=clevercanyon.com";

	# Intermediate CSR.

	openssl req -config ./.ssl-openssl.cnf -extensions v3_req \
		-new \
		-nodes \
		-sha512 \
		-key ./.ssl-i-ca-key.pem \
		-out ./.ssl-i-ca-csr.pem \
		-subj "/C=US/ST=GA/L=Johns Creek/O=Clever Canyon/OU=Engineering/CN=clevercanyon.com";

	# Intermediate CA for CSR.

	openssl ca -config ./.ssl-openssl.cnf -extensions v3_ca \
		-notext \
		-batch \
		-md sha256 \
		-days "${days}" \
		-rand_serial \
		-cert ./.ssl-r-ca-crt.pem \
		-keyfile ./.ssl-r-ca-key.pem \
		-in ./.ssl-i-ca-csr.pem \
		-out ./.ssl-i-ca-crt.pem;

	# Cleanup config directory.

	rm -rf ./.ssl-openssl;
fi;
if [[ "${1:-}" == 'add-to-mac-keychain' ]]; then # Tell macOS to trust these.
	sudo security -v add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain ./.ssl-r-ca-crt.pem;
	sudo security -v add-trusted-cert -d -r trustAsRoot -k /Library/Keychains/System.keychain ./.ssl-i-ca-crt.pem;
fi;
