##
# Clever Canyon™ {@see https://clevercanyon.com}
#
#  CCCCC  LL      EEEEEEE VV     VV EEEEEEE RRRRRR      CCCCC    AAA   NN   NN YY   YY  OOOOO  NN   NN ™
# CC      LL      EE      VV     VV EE      RR   RR    CC       AAAAA  NNN  NN YY   YY OO   OO NNN  NN
# CC      LL      EEEEE    VV   VV  EEEEE   RRRRRR     CC      AA   AA NN N NN  YYYYY  OO   OO NN N NN
# CC      LL      EE        VV VV   EE      RR  RR     CC      AAAAAAA NN  NNN   YYY   OO   OO NN  NNN
#  CCCCC  LLLLLLL EEEEEEE    VVV    EEEEEEE RR   RR     CCCCC  AA   AA NN   NN   YYY    OOOO0  NN   NN
##

##
# WP docker compose file (project-specific).
#
# @since 1.0.0
#
# You *can* edit this file. It can contain project-specific overrides.
# This file is automatically detected by PHP scripts and merged into `./dev/.libs/docker/wp/compose.yml`.
#
# @see https://docs.docker.com/compose/extends/
##

version : '3.9' # {@see https://o5p.me/TtD60s}.

# Your code here.
