/**
 * Webpack config file.
 *
 * @since 1.0.0
 *
 * @note Webpack is aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * This file and the contents of it are updated automatically.
 * Instead of editing, please configure `composer.json`. See instructions below.
 * Instead of editing, please see source repository @ <https://git.io/JD8Zo>.
 */
/* eslint-env node */

/* @formatter:ignore
-----------------------------------------------------------------------------------------------------------------------
Example `extra.clevercanyon.&.webpack` using `composer.json`:
-----------------------------------------------------------------------------------------------------------------------
"extra" : {
	"clevercanyon" : {
		"&" : {
			"webpack" : {
				"assetDirs" : [ "./src/assets" ]
			}
		}
	}
}
-----------------------------------------------------------------------------------------------------------------------
Example directory structure expected for webpack:
-----------------------------------------------------------------------------------------------------------------------
./src/assets (or any other location)
	- styles/index.scss
	- scripts/index.js
	- webpack/ (output directory)
------------------------------------------------------------------------------------------------- @formatter:/ignore */

const path    = require( 'path' );
const miniCss = require( 'mini-css-extract-plugin' );
const mc      = require( '@clevercanyon/js-object-mc' );

module.exports = ( env, argv ) => {
	const file = {
		'composer.json' : {},
		'package.json'  : {},
	};
	try { file[ 'composer.json' ] = require( '../composer.json' ); } catch ( e ) {}
	try { file[ 'package.json' ] = require( '../package.json' ); } catch ( e ) {}

	const configs = [];
	const config  = mc.merge(
		{
			assetDirs : [ './src/assets' ], // Resolved below.
			config    : {}, // Merges into all base config values.
		},
		file[ 'composer.json' ]?.extra?.clevercanyon?.[ '&' ]?.webpack || {},
		file[ 'package.json' ]?.config?.clevercanyon?.[ '&' ]?.webpack || {},
	);

	( config.assetDirs || [] ).forEach( ( assetsDir ) => {
		assetsDir = path.resolve( __dirname, '../' + assetsDir );

		configs.push( mc.merge( {
			cache   : false,
			mode    : 'production',
			target  : 'browserslist',
			plugins : [ new miniCss( { filename : '[name].min.css' } ) ],
			module  : {
				rules : [
					{
						test : /\.(?:txt|md)$/i,
						use  : [ 'raw-loader' ],
					},
					{
						test : /\.(?:html)$/i,
						use  : [ 'html-loader' ],
					},
					{
						test : /\.(?:gif|jpe?g|png|svg|eot|ttf|woff[0-9]*)$/i,
						use  : [ 'file-loader' ],
					},
					{
						test : /\.(?:css|scss)$/i,
						use  : [ miniCss.loader, 'css-loader', 'postcss-loader', 'sass-loader' ],
					},
					{
						test    : /\.(?:js|jsx)$/i,
						exclude : [ /\/(?:node_modules\/(?:core-js|webpack\/buildin))\//i ],
						use     : [ 'babel-loader', '@linaria/webpack-loader' ],
					},
				],
			},
			entry   : {
				index : [
					assetsDir + '/styles/index.scss',
					assetsDir + '/scripts/index.js',
				],
			},
			output  : {
				path     : assetsDir + '/webpack',
				filename : '[name].min.js',
			},
		}, config.config || {} ) );
	} );

	return configs;
};
